import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SectionWrapper from "@/components/layout/section-wrapper";
import localFont from 'next/font/local'
import { Toaster } from "@/components/ui/sonner";
import { CheckoutProvider } from "@/context/checkout-context";
import { createClient } from "@/lib/supabase/supabase-ssr";

const myFont = localFont({
  src: './fonts/Poppins-Regular.ttf',
  variable: '--font-poppins',
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

   


  return (
    <html lang="en">
      <body
        className={`bg-calm-secondary ${myFont.className} antialiased`}
      >
            <CheckoutProvider>
          
        {children}
 <Toaster richColors position="top-right"/>
    </CheckoutProvider>

      </body>
    </html>
  );
}
