import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SectionWrapper from "@/components/layout/section-wrapper";
import localFont from 'next/font/local'

const myFont = localFont({
  src: './fonts/Poppins-Regular.ttf',
  variable: '--font-poppins',
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${myFont.className} antialiased`}
      >
        <SectionWrapper>
        {children}
        </SectionWrapper>
      </body>
    </html>
  );
}
